#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CSApplication.Resource", IsApplication=true)]

namespace CSApplication
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int familydoctor = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int next = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int previous = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int star = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060018
			public const int DataHeader = 2131099672;
			
			// aapt resource value: 0x7f060000
			public const int DataId = 2131099648;
			
			// aapt resource value: 0x7f060012
			public const int btnKirim = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int button1 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int expandableListView1 = 2131099665;
			
			// aapt resource value: 0x7f06001c
			public const int fragment1 = 2131099676;
			
			// aapt resource value: 0x7f06000f
			public const int idNext = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int idPrev = 2131099662;
			
			// aapt resource value: 0x7f060004
			public const int imageView1 = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout1 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout2 = 2131099661;
			
			// aapt resource value: 0x7f06001b
			public const int listDepartemen = 2131099675;
			
			// aapt resource value: 0x7f060007
			public const int listDetailPertanyaan = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int listDokter = 2131099657;
			
			// aapt resource value: 0x7f060015
			public const int listPertanyaanRj = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int listPoli = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int lvDetail = 2131099668;
			
			// aapt resource value: 0x7f06000c
			public const int lvPertanyaan = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int nameDepartment = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int radioButton1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int radioButton2 = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int radioGroup1 = 2131099649;
			
			// aapt resource value: 0x7f060019
			public const int relativeLayout1 = 2131099673;
			
			// aapt resource value: 0x7f060008
			public const int textDetailPertanyaan = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int textDokter = 2131099658;
			
			// aapt resource value: 0x7f060013
			public const int textPertanyaan = 2131099667;
			
			// aapt resource value: 0x7f060017
			public const int textPoli = 2131099671;
			
			// aapt resource value: 0x7f060005
			public const int textView1 = 2131099653;
			
			// aapt resource value: 0x7f06001a
			public const int textView2 = 2131099674;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DataListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int layout_departemen_adapter = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int layout_detail_pertanyaan = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int layout_detail_pertanyaan_adapter = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int layout_dokter = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int layout_dokter_adapter = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int layout_pager = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int layout_pertanyaan = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int layout_pertanyaan_adapter = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int layout_pertanyaan_fragment = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int layout_pertanyaan_rj = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int layout_poli = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int layout_poli_adapter = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ListGroup = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Main = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int result = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int test = 2130903057;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int bantukami = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int pilihlayanan = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int AlertDialogCustom = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int MyApp_DialogButton = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int MyCustomTheme = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int Theme_NoTitle = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
